config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  # root :to => 'metafields#new'

  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/products', to: "products#index", as: :products
  get '/products/:id', to: "products#show", as: :product

  resources :metafields

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/metafield.rb
class Metafield < ShopifyAPI::Metafield
    attributes = [:namespace, :key, :value, :value_type, :description, :owner_id, :owner_resource]
  
    attributes.each do |attr|
      attr_accessor attr
  
      define_method attr.to_sym do
        @attributes[attr.to_sym]
      end
    end
  
  end
  

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::ShopSessionStorage

  def api_version
    ShopifyApp.configuration.api_version
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class ProductsController < AuthenticatedController
  def index
    # @products = ShopifyAPI::Product.find(:all, params: { limit: 1, page: 1 })
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    @webhooks = ShopifyAPI::Webhook.find(:all)
  end

  def show
    Struct.new("Metafield", :src, :alt)

    @product = ShopifyAPI::Product.find(params[:id])
    @images = []

    # store header for request call to Shopify API
    headers = {"X-Shopify-Access-Token" => @current_shopify_session.token}

    @metafields = HTTParty.get('https://store88-myshopif.myshopify.com/admin/metafields.json?metafield[owner_id]=' +
                                params[:id] +'&metafield[owner_resource]=product',
                                :headers => headers).values[0].map { |metafield| OpenStruct.new metafield }



    # @product.images.each do |image|
    #   id = image.id.to_s
    #   src = image.src
    #
    #   #make the request and store it in a variable
    #   metafields = HTTParty.get('https://quyet-akronym-store.myshopify.com/admin/metafields.json?metafield[owner_id]=' +
    #                                 id +'&metafield[owner_resource]=product_image',
    #                             :headers => headers).values
    #
    #   metafields.first.present? ? alt = metafields.first['value'] : alt = @product.title
    #
    #   image = Struct::Image.new(src, alt)
    #
    #   #add the returned data to the @image_metafiels array
    #   @images.push(image)
    # end
  end

end

app/controllers/metafields_controller.rb
class MetafieldsController < AuthenticatedController
    before_action :set_metafield, only: [:destroy, :edit, :update]
  
    def index
    end
  
    def new
      @owner_class = params[:owner_class] ? params[:owner_class] : 'Product'
      @owner_id = params[:owner_id] ? params[:owner_id] : ShopifyAPI::Product.find(:all).first.id
      @owner = Object.const_get("ShopifyAPI::#{@owner_class}").find(@owner_id)
      @metafield = Metafield.new
    end
  
    def edit
      @owner_class = @metafield.owner_resource
      @owner_id = @metafield.owner_id
    end
  
    def update
      # NAMESPACE & KEY cannot be changed for existing record
      @metafield.attributes.merge! metafield_params
      @metafield.save
  
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
  
    def create
      metafield = Metafield.new(params[:metafield].as_json)
      if metafield.valid?
        metafield.save
      end
  
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
  
    def destroy
      @metafield.destroy
      @destroy_redirect_path = product_path(@owner)
      redirect_to @destroy_redirect_path
    end
  
    private
  
    def set_metafield
      @metafield = Metafield.find(params[:id])
  
      case @metafield.owner_resource
      when 'product'
        @owner = ShopifyAPI::Product.find(@metafield.owner_id)
      end
    end
  
    def metafield_params
      params.require(:metafield).permit(:namespace, :key, :value, :value_type, :description, :owner_id, :owner_resource)
    end
  end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < AuthenticatedController
    def index
      # @products = ShopifyAPI::Product.find(:all, params: { limit: 1, page: 1 })

      @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
      @webhooks = ShopifyAPI::Webhook.find(:all)
    end
  
    def show
      Struct.new("Metafield", :src, :alt)
  
      @product = ShopifyAPI::Product.find(params[:id])
      @images = []
  
      # store header for request call to Shopify API
      headers = {"X-Shopify-Access-Token" => @current_shopify_session.token}

      @metafields = HTTParty.get('https://store88-myshopif.myshopify.com/admin/metafields.json?metafield[owner_id]=' +
                                  params[:id] +'&metafield[owner_resource]=product',
                                  :headers => headers).values[0].map { |metafield| OpenStruct.new metafield }
  
  
  
      # @product.images.each do |image|
      #   id = image.id.to_s
      #   src = image.src
      #
      #   #make the request and store it in a variable
      #   metafields = HTTParty.get('https://quyet-akronym-store.myshopify.com/admin/metafields.json?metafield[owner_id]=' +
      #                                 id +'&metafield[owner_resource]=product_image',
      #                             :headers => headers).values
      #
      #   metafields.first.present? ? alt = metafields.first['value'] : alt = @product.title
      #
      #   image = Struct::Image.new(src, alt)
      #
      #   #add the returned data to the @image_metafiels array
      #   @images.push(image)
      # end
    end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  


    <%= yield %>




  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <% if ShopifyApp.use_webpacker? %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <% end %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://unpkg.com/@shopify/app-bridge"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: (@current_shopify_session.domain if @current_shopify_session),
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/layouts_old/_flash_messages.html.erb
<% content_for :javascript do %>
  <%= content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } }) %>
<% end %>

app/views/layouts_old/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeShopify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts_old/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main"  id="page-wrapper">

          <%= render 'shared/header' %>
          <%= yield %>

        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: ("https://#{ @shop_session.url }" if @shop_session),
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/metafields/_form.html.erb
<div id="custom-breadcumb">
  <span class="text-secondary"><%= @owner_class %> > <%= @owner.title %> </span> >
  <%= @metafield.id ? "Edit" : "New" %> Metafield
</div>

<div id="custom-form-container">
    <%= bootstrap_form_for @metafield do |mf| %>
      <%#= f.fields_for :metafield do |mf| %>
        <%= mf.hidden_field :owner_id, value: @owner_id %>
        <%= mf.hidden_field :owner_resource, value: @owner_class.downcase %>
        <%= mf.text_field :namespace, label: 'Namespace', placeholder: 'Namespace of metafield' %>
        <%= mf.text_field :key,label: 'Key', placeholder: 'Key of metafield' %>
        <%= mf.text_field :value,label: 'Value', placeholder: 'Key of metafield' %>
        <%= mf.select :value_type, [['String', 'string']], label: 'Type', class: 'selectpicker' %>
        <%= mf.text_area :description, label: 'Description', placeholder: 'Description about metafield' %>
      <%# end %>

      <%= mf.submit 'Submit', class: 'btn btn-outline-dark float-right' %>
<% end %>
</div>

app/views/metafields/_shopify_bar.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      <% if @owner %>
        ShopifyApp.Bar.initialize({ title: "Metafields" });
      <% end  %>
    });
  </script>
<% end %>

app/views/metafields/edit.html.erb
<%= render partial: 'shopify_bar' %>
<%= render partial: 'form' %>

app/views/metafields/new.html.erb
<%= render partial: 'shopify_bar' %>
<%= render partial: 'form' %>

app/views/products/_shopify_bar.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Products / <%= @product.title %>" });
    });
  </script>
<% end %>

app/views/products/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home" });
    });
  </script>
<% end %>

<div class="row" id="products-list">
  <div class="col-md-12">
    <table class="table">
      <thead class="thead-light">
      <tr>
      
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Image</th>
        <th scope="col">Type</th>
        <th scope="col">Vendor</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @products.each_with_index do |product, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= product.title %></td>
          <td><%= image_tag product.image.src, alt: "Product Image",class: 'img-thumbnail small-img-thumbnail' %></td>
          <td><%= product.product_type %></td>
          <td><%= product.vendor %></td>
          <td>
            <%= link_to "Metafields", product_path(product), class: "btn btn-link" %>

            # <%= link_to "Admin", "https://#{@current_shopify_session.domain}/admin/products/#{product.id}", target: "_top", class: "btn btn-link" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<% if false %>
  <h2>Webhooks</h2>

  <% if @webhooks.present? %>
    <ul>
      <% @webhooks.each do |webhook| %>
        <li><%= webhook.topic %> : <%= webhook.address %></li>
      <% end %>
    </ul>
  <% else %>
    <p>This app has not created any webhooks for this Shop. Add webhooks to your ShopifyApp initializer if you need webhooks</p>
  <% end %>
<% end %>

app/views/products/show.html.erb
<%= render partial: 'shopify_bar' %>

<h2  id="product-title">
  <div class="float-left">
    <span> <%= @product.title %> </span>
    <img src="<%= @product.image.src %>" class="img-thumbnail small-img-thumbnail" />
  </div>

  <div class="float-right">
    <%= link_to 'New Metafield', new_metafield_path(owner_id: @product.id, owner_class: 'Product'), class: 'btn btn-outline-primary'%>
  </div>
</h2>

<table class="table">
  <thead class="thead-light">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Namespace</th>
    <th scope="col">Key</th>
    <th scope="col">Type</th>
    <th scope="col">Value</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>

  <tbody>
    <% @metafields.each_with_index do |metafield, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= metafield.namespace %></td>
        <td><%= metafield.key %></td>
        <td><%= metafield.value_type %></td>
        <td><%= metafield.value %></td>
        <td>
          <%= link_to "Edit", edit_metafield_path(metafield.id), class: "btn btn-link" %>

          <%= link_to "Delete", metafield_path(metafield.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-link" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Products", products_path, class: "nav-item nav-link active" %>

      <!--
      <a class="nav-item nav-link" href="#">Collection</a>
      <a class="nav-item nav-link" href="#">Order</a>
      <a class="nav-item nav-link" href="#">Shop</a>
      <a class="nav-item nav-link" href="#">Customer</a>
      <a class="nav-item nav-link" href="#">Page</a>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Others</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Write us review</a>
          <a class="dropdown-item" href="#">Contact us</a>
        </div>
      </li>
      -->

    </div>
  </div>
</nav>